// Base de la app: "/" en dev, "./" en el build de GitHub Pages. Con fallback para Node (verify-course).
const assetBase = (typeof import.meta !== "undefined" && import.meta.env?.BASE_URL) || "/";

function officialAsset(file) {
  return `${assetBase}assets/wonderblocks-official/${file}`;
}

export const sourceVideos = {
  intro: {
    id: "OPTxITAkl_0",
    title: "An Introduction to Wonderblocks - Start Here!",
  },
  goStop: {
    id: "E2jnsOm24yQ",
    title: "Let's Play Go and Stop!",
  },
  stopSetGo: {
    id: "WOMKhpyk3JU",
    title: "Stop, Get Set, GO!",
  },
  instructions: {
    id: "Kwrh-t-lkA4",
    title: "How to Read Instructions",
  },
  rainbow: {
    id: "rrBsVme7Ohc",
    title: "A Rainbow of Do Blocks",
  },
  animals: {
    id: "3QgsGJ5YIic",
    title: "All the Animal Sound Do-Blocks!",
  },
  loops: {
    id: "dwu2K_O75Ro",
    title: "Loops, Hops, Patterns & More!",
  },
  infinite: {
    id: "TDkMN9VYSxM",
    title: "The Infinite Code!",
  },
};

export const characters = {
  start: {
    name: "Start",
    role: "enciende cada aventura",
    shape: "circle",
    colors: ["#5ee66b", "#159447"],
    origin: "inventado para el curso",
    asset: officialAsset("group-stop-go.avif"),
    assetLabel: "asset oficial Go + Stop",
  },
  go: {
    name: "Go",
    role: "da el paso valiente",
    shape: "squircle",
    colors: ["#3ee0b7", "#087a64"],
    origin: "Wonderblocks",
    asset: officialAsset("go.avif"),
    assetLabel: "asset oficial Go",
  },
  stop: {
    name: "Stop",
    role: "para, mira y piensa",
    shape: "octagon",
    colors: ["#ff5b4d", "#a61f1b"],
    origin: "Wonderblocks",
    asset: officialAsset("stop.avif"),
    assetLabel: "asset oficial Stop",
  },
  again: {
    name: "Again",
    role: "repite patrones sin cansarse",
    shape: "loop",
    colors: ["#ffd24a", "#d18300"],
    origin: "Wonderblocks",
    asset: officialAsset("again.avif"),
    assetLabel: "asset oficial Again",
  },
  arty: {
    name: "Arty",
    role: "pinta instrucciones",
    shape: "stamp",
    colors: ["#78b7ff", "#2959bc"],
    origin: "Wonderblocks Splat/paint reference",
    asset: officialAsset("splat-purple.avif"),
    assetLabel: "asset oficial Splat",
  },
  hop: {
    name: "Hop",
    role: "salta obstaculos",
    shape: "triangle",
    colors: ["#ff8ac1", "#b22972"],
    origin: "Wonderblocks",
    asset: officialAsset("hop.avif"),
    assetLabel: "asset oficial Hop",
  },
  moo: {
    name: "Moo",
    role: "activa sonidos graves",
    shape: "cow",
    colors: ["#fff8df", "#2e3b3d"],
    origin: "Wonderblocks animal Do-Blocks",
    asset: officialAsset("moo.avif"),
    assetLabel: "asset oficial Moo",
  },
  cluck: {
    name: "Cluck",
    role: "activa sonidos rapidos",
    shape: "beak",
    colors: ["#ffe37a", "#f07a2a"],
    origin: "Wonderblocks animal Do-Blocks",
    asset: officialAsset("cluck.avif"),
    assetLabel: "asset oficial Cluck",
  },
  nina: {
    name: "Nina Nodo",
    role: "une ideas en caminos",
    shape: "hex",
    colors: ["#b191ff", "#6041bd"],
    origin: "inventado",
  },
  byte: {
    name: "Byte Brillo",
    role: "guarda estrellas de progreso",
    shape: "star",
    colors: ["#7ee7f0", "#1888a0"],
    origin: "inventado",
  },
};

export const commandCatalog = {
  start: {
    label: "Start",
    short: "ON",
    action: "Enciende el programa antes de mover.",
    tone: "#5ee66b",
  },
  go: {
    label: "Go",
    short: "GO",
    action: "Avanza una casilla.",
    tone: "#3ee0b7",
  },
  stop: {
    label: "Stop",
    short: "ST",
    action: "Detiene el programa en el momento justo.",
    tone: "#ff5b4d",
  },
  left: {
    label: "Gira izquierda",
    short: "GI",
    action: "Mira al lado izquierdo.",
    tone: "#f3a53b",
  },
  right: {
    label: "Gira derecha",
    short: "GD",
    action: "Mira al lado derecho.",
    tone: "#8f7cf6",
  },
  wait: {
    label: "Espera",
    short: "PA",
    action: "Hace una pausa en una casilla.",
    tone: "#8bd7f3",
  },
  hop: {
    label: "Hop",
    short: "HP",
    action: "Salta sobre un charco y cae dos casillas despues.",
    tone: "#ff8ac1",
  },
  again2: {
    label: "Again x2",
    short: "x2",
    action: "Repite dos veces el bloque siguiente.",
    tone: "#ffd24a",
  },
  again3: {
    label: "Again x3",
    short: "x3",
    action: "Repite tres veces el bloque siguiente.",
    tone: "#ffd24a",
  },
  ifSignalGo: {
    label: "Si hay señal, Go",
    short: "SI",
    action: "Avanza solo si la casilla de delante tiene señal.",
    tone: "#86d965",
  },
  paint: {
    label: "Pinta",
    short: "PI",
    action: "Colorea la casilla donde estas.",
    tone: "#78b7ff",
  },
  moo: {
    label: "Moo",
    short: "MU",
    action: "Toca el Do-Block de vaca.",
    tone: "#f9f1dc",
  },
  cluck: {
    label: "Cluck",
    short: "CL",
    action: "Toca el Do-Block de gallina.",
    tone: "#ffe37a",
  },
  bridge: {
    label: "Rutina puente",
    short: "RU",
    action: "Ejecuta Go, Go, gira derecha.",
    tone: "#ef7f45",
  },
};

export const courseModules = [
  {
    id: "m1-start-stop",
    order: 1,
    title: "Start, Stop, Go",
    subtitle: "Secuencias cortas y control",
    source: ["intro", "goStop", "stopSetGo"],
    color: "#5ee66b",
    levelIds: ["wake-up-wonderland", "red-green-gate", "start-stop-story", "sun-chase"],
  },
  {
    id: "m2-read-plan",
    order: 2,
    title: "Leer instrucciones",
    subtitle: "Pistas, turnos y planes",
    source: ["instructions"],
    color: "#8bd7f3",
    levelIds: ["muddy-welly-plan", "breakfast-bears", "arrow-map"],
  },
  {
    id: "m3-do-blocks",
    order: 3,
    title: "Do-Blocks",
    subtitle: "Pintar, sonar y combinar acciones",
    source: ["rainbow", "animals"],
    color: "#78b7ff",
    levelIds: ["rainbow-do-blocks", "animal-sound-trail", "arty-paint-party"],
  },
  {
    id: "m4-again-loops",
    order: 4,
    title: "Again y patrones",
    subtitle: "Bucles, saltos y codigo largo",
    source: ["loops", "infinite"],
    color: "#ffd24a",
    levelIds: ["again-rainbow-path", "hop-pattern", "again-stair", "finite-infinite"],
  },
  {
    id: "m5-code-camp",
    order: 5,
    title: "Code Camp",
    subtitle: "Depurar, decidir y crear rutinas",
    source: ["goStop", "instructions", "loops", "infinite"],
    color: "#b191ff",
    levelIds: ["debug-stop", "condition-forest", "routine-bridge", "graduation-wondercode"],
  },
];

// Dificultad: dentro de cada modulo la solucion crece en bloques.
// M1: 4-5-7-9 | M2: 5-6-6 | M3: 7-8-9 | M4: 4-5-7-7 | M5: 4-6-6-15.
export const challenges = [
  {
    id: "wake-up-wonderland",
    moduleId: "m1-start-stop",
    order: 1,
    title: "Despierta Wonderland",
    skill: "Secuencia",
    character: "start",
    readingLevel: "Frases muy cortas",
    source: ["intro"],
    requiresStart: true,
    requiresStop: true,
    story:
      "Hoy Wonderland amanece dormida: la estrella de la puerta se apagó anoche. Go quiere correr hacia ella, pero sin Start la máquina no arranca. Enciende el programa, da dos pasos exactos hasta la estrella y cierra con Stop antes de tocar la pared.",
    dialogue: "¡Luces encendidas! Preparados, listos... ¡GO!",
    prompt: "¿Qué bloque enciende la máquina antes de caminar?",
    vocabulary: ["Start", "Go", "Stop"],
    objective: "Aprende una secuencia completa: Start, pasos Go y Stop final.",
    toolbox: ["start", "go", "stop"],
    solution: ["start", "go", "go", "stop"],
    board: {
      cols: 5,
      rows: 5,
      start: { x: 0, y: 2, dir: "E" },
      target: { x: 2, y: 2 },
      collectibles: [{ x: 2, y: 2, label: "estrella" }],
      walls: [{ x: 3, y: 2 }],
    },
  },
  {
    id: "red-green-gate",
    moduleId: "m1-start-stop",
    order: 2,
    title: "La verja roja y verde",
    skill: "Parar a tiempo",
    character: "stop",
    readingLevel: "Lectura de señal",
    source: ["goStop", "stopSetGo"],
    requiresStart: true,
    requiresStop: true,
    story:
      "Go ha visto una gema brillante y sale disparado sin mirar. Stop levanta la mano: justo detrás de la gema espera la verja roja. Tres pasos valientes y un freno a tiempo, así se gana este capítulo.",
    dialogue: "¡Stop! Primero mira, luego corre.",
    prompt: "¿Por qué Stop debe aparecer justo al llegar a la gema?",
    vocabulary: ["rojo", "verde", "parar"],
    objective: "Controla el final del programa: llega a la gema y para a tiempo.",
    toolbox: ["start", "go", "stop"],
    solution: ["start", "go", "go", "go", "stop"],
    board: {
      cols: 5,
      rows: 3,
      start: { x: 0, y: 1, dir: "E" },
      target: { x: 3, y: 1 },
      collectibles: [{ x: 3, y: 1, label: "gema" }],
      walls: [{ x: 4, y: 1 }],
    },
  },
  {
    id: "start-stop-story",
    moduleId: "m1-start-stop",
    order: 3,
    title: "Cuento de dos botones",
    skill: "Programa completo",
    character: "stop",
    readingLevel: "Mini cuento",
    source: ["intro", "stopSetGo"],
    requiresStart: true,
    requiresStop: true,
    story:
      "Start abre el libro mecánico de Wonderland y Stop lo cierra con cuidado para que no se doblen las páginas. Entre los dos hay un pasillo con una esquina traviesa. Si al cuento le falta una parte, las páginas salen volando.",
    dialogue: "Un cuento sin final es un lío: ciérralo justo a tiempo.",
    prompt: "¿Cuáles son las tres partes de un programa completo?",
    vocabulary: ["inicio", "acciones", "cierre"],
    objective: "Construye un programa con inicio, acciones de movimiento y cierre.",
    toolbox: ["start", "go", "right", "left", "stop"],
    solution: ["start", "go", "go", "right", "go", "go", "stop"],
    board: {
      cols: 5,
      rows: 5,
      start: { x: 0, y: 0, dir: "E" },
      target: { x: 2, y: 2 },
      collectibles: [{ x: 2, y: 2, label: "libro" }],
      walls: [
        { x: 3, y: 0 },
        { x: 3, y: 1 },
        { x: 0, y: 2 },
      ],
    },
  },
  {
    id: "sun-chase",
    moduleId: "m1-start-stop",
    order: 4,
    title: "Persigue el sol",
    skill: "Giros",
    character: "go",
    readingLevel: "Camino en orden",
    source: ["goStop"],
    requiresStart: true,
    requiresStop: true,
    story:
      "El sol juega al escondite y rueda por un camino lleno de esquinas. Go no puede improvisar: dos pasos, un giro, dos pasos más y un último ajuste antes de tocarlo. ¡En este capítulo cada giro cuenta!",
    dialogue: "¡A por el sol! Paso a paso y sin saltarme ninguna esquina.",
    prompt: "¿Cuántos Go van antes del primer giro?",
    vocabulary: ["pasos", "giro", "alcanzar"],
    objective: "Lee un camino con giros y coloca cada paso en orden.",
    toolbox: ["start", "go", "left", "right", "stop"],
    solution: ["start", "go", "go", "left", "go", "go", "right", "go", "stop"],
    board: {
      cols: 5,
      rows: 5,
      start: { x: 0, y: 3, dir: "E" },
      target: { x: 3, y: 1 },
      collectibles: [{ x: 3, y: 1, label: "sol" }],
      walls: [
        { x: 1, y: 1 },
        { x: 3, y: 2 },
        { x: 4, y: 3 },
      ],
    },
  },
  {
    id: "muddy-welly-plan",
    moduleId: "m2-read-plan",
    order: 5,
    title: "Botas en el barro",
    skill: "Planificar salto",
    character: "hop",
    readingLevel: "Problema y solucion",
    source: ["instructions"],
    requiresStart: true,
    requiresStop: true,
    story:
      "¡Plof! Un charco de barro enorme corta el camino y salpica a quien pasa andando. Hop estira sus muelles y lee el plan: acércate con un paso, salta por encima del charco y aterriza en suelo seco.",
    dialogue: "¿Un charco? ¡Boing! Para eso están los saltos.",
    prompt: "¿Qué bloque sirve para pasar por encima del charco?",
    vocabulary: ["barro", "saltar", "plan"],
    objective: "Distingue caminar de saltar: usa Hop solo ante el obstáculo.",
    toolbox: ["start", "go", "hop", "stop"],
    solution: ["start", "go", "hop", "go", "stop"],
    board: {
      cols: 5,
      rows: 4,
      start: { x: 0, y: 2, dir: "E" },
      target: { x: 4, y: 2 },
      collectibles: [{ x: 4, y: 2, label: "bota seca" }],
      water: [{ x: 2, y: 2 }],
    },
  },
  {
    id: "breakfast-bears",
    moduleId: "m2-read-plan",
    order: 6,
    title: "Turno de los osos",
    skill: "Esperar",
    character: "nina",
    readingLevel: "Pista social",
    source: ["instructions"],
    requiresStart: true,
    requiresStop: true,
    story:
      "En la mesa de los osos solo hay una cuchara dorada y todos quieren desayunar a la vez. Nina Nodo lee la norma en voz alta: avanza, espera tu turno en la baldosa marcada y sigue cuando el camino quede libre.",
    dialogue: "Esperar también es parte del plan.",
    prompt: "¿Qué bloque representa esperar sin moverte?",
    vocabulary: ["esperar", "turno", "orden"],
    objective: "Usa Espera como una pausa dentro de la secuencia.",
    toolbox: ["start", "go", "wait", "stop"],
    solution: ["start", "go", "wait", "go", "go", "stop"],
    board: {
      cols: 5,
      rows: 3,
      start: { x: 0, y: 1, dir: "E" },
      target: { x: 3, y: 1 },
      waitTiles: [{ x: 1, y: 1 }],
      collectibles: [{ x: 3, y: 1, label: "cuchara" }],
    },
  },
  {
    id: "arrow-map",
    moduleId: "m2-read-plan",
    order: 7,
    title: "Mapa de flechas verdes",
    skill: "Condicion simple",
    character: "nina",
    readingLevel: "Si... entonces",
    source: ["instructions"],
    requiresStart: true,
    requiresStop: true,
    story:
      "Nina Nodo encuentra hojas con lucecitas verdes escondidas en el mapa. El bloque Si no es magia: mira la casilla de delante y solo deja avanzar cuando hay señal. Así es como un programa decide con información de verdad.",
    dialogue: "Si hay señal... ¡entonces adelante!",
    prompt: "Completa la regla: si hay señal, entonces...",
    vocabulary: ["si", "entonces", "señal"],
    objective: "Introduce una condición: avanzar solo cuando la señal lo permite.",
    toolbox: ["start", "ifSignalGo", "go", "right", "left", "stop"],
    solution: ["start", "ifSignalGo", "go", "left", "ifSignalGo", "stop"],
    board: {
      cols: 4,
      rows: 4,
      start: { x: 0, y: 2, dir: "E" },
      target: { x: 2, y: 1 },
      signals: [
        { x: 1, y: 2 },
        { x: 2, y: 1 },
      ],
      collectibles: [{ x: 2, y: 1, label: "mapa" }],
      walls: [{ x: 3, y: 2 }],
    },
  },
  {
    id: "rainbow-do-blocks",
    moduleId: "m3-do-blocks",
    order: 8,
    title: "Arcoiris Do-Block",
    skill: "Acciones",
    character: "arty",
    readingLevel: "Instrucciones con color",
    source: ["rainbow"],
    requiresStart: true,
    requiresStop: true,
    story:
      "Las tres baldosas del arcoíris se han quedado sin color después de la tormenta. Arty prepara su sello mágico: pinta, da un paso, vuelve a pintar. Si sella antes o después de tiempo, el arcoíris queda a rayas.",
    dialogue: "¡Splat! Un sello en cada baldosa, ni uno más.",
    prompt: "¿Qué acción debe repetirse en cada baldosa de color?",
    vocabulary: ["accion", "color", "orden"],
    objective: "Combina movimiento y acción: pintar, avanzar y volver a pintar.",
    toolbox: ["start", "paint", "go", "stop"],
    solution: ["start", "paint", "go", "paint", "go", "paint", "stop"],
    board: {
      cols: 5,
      rows: 4,
      start: { x: 1, y: 1, dir: "E" },
      target: { x: 3, y: 1 },
      paintTiles: [
        { x: 1, y: 1 },
        { x: 2, y: 1 },
        { x: 3, y: 1 },
      ],
    },
  },
  {
    id: "animal-sound-trail",
    moduleId: "m3-do-blocks",
    order: 9,
    title: "Sendero Moo-Cluck",
    skill: "Eventos",
    character: "moo",
    readingLevel: "Sonidos del camino",
    source: ["animals"],
    requiresStart: true,
    requiresStop: true,
    story:
      "El sendero de la granja esconde dos botones musicales. Moo suena grave en su casilla y Cluck canta rápido en la suya. El programa debe tocar cada sonido justo donde vive, o el concierto del camino se desafina.",
    dialogue: "Muuu... cada sonido en su casilla.",
    prompt: "¿Qué sonido se activa primero en el camino?",
    vocabulary: ["sonido", "evento", "correcto"],
    objective: "Aprende eventos: ejecutar la acción correcta en la casilla correcta.",
    toolbox: ["start", "go", "moo", "cluck", "stop"],
    solution: ["start", "go", "moo", "go", "go", "cluck", "go", "stop"],
    board: {
      cols: 5,
      rows: 3,
      start: { x: 0, y: 1, dir: "E" },
      target: { x: 4, y: 1 },
      soundGoals: [
        { x: 1, y: 1, command: "moo", label: "Moo" },
        { x: 3, y: 1, command: "cluck", label: "Cluck" },
      ],
      collectibles: [{ x: 4, y: 1, label: "flor" }],
    },
  },
  {
    id: "arty-paint-party",
    moduleId: "m3-do-blocks",
    order: 10,
    title: "Fiesta de Arty",
    skill: "Combinar acciones",
    character: "arty",
    readingLevel: "Lista de pasos",
    source: ["rainbow"],
    requiresStart: true,
    requiresStop: true,
    story:
      "¡Fiesta en casa de Arty! El dibujo de esta noche tiene esquina: dos sellos en línea y uno arriba. La trampa del capítulo es girar después de pintar la segunda baldosa, ni antes ni después.",
    dialogue: "Pinta, pinta... ¡y gira en el momento justo!",
    prompt: "¿Después de qué baldosa aparece el giro?",
    vocabulary: ["lista", "giro", "hueco"],
    objective: "Planifica una acción con cambio de dirección.",
    toolbox: ["start", "go", "paint", "left", "right", "stop"],
    solution: ["start", "go", "paint", "go", "paint", "left", "go", "paint", "stop"],
    board: {
      cols: 5,
      rows: 4,
      start: { x: 0, y: 2, dir: "E" },
      target: { x: 2, y: 1 },
      paintTiles: [
        { x: 1, y: 2 },
        { x: 2, y: 2 },
        { x: 2, y: 1 },
      ],
    },
  },
  {
    id: "again-rainbow-path",
    moduleId: "m4-again-loops",
    order: 11,
    title: "Again abre el puente",
    skill: "Bucle simple",
    character: "again",
    readingLevel: "Patron corto",
    source: ["loops"],
    requiresStart: true,
    requiresStop: true,
    story:
      "El puente del tambor solo se abre con tres golpes iguales: paso, paso, paso. Again bosteza mirando la fila de bloques repetidos. ¿Para qué escribir tres Go seguidos si puede decir una sola vez 'repite x3'?",
    dialogue: "¡Otra vez, otra vez, otra vez! Eso es un bucle.",
    prompt: "¿Qué bloque se repite tres veces dentro del bucle?",
    vocabulary: ["repetir", "patron", "energia"],
    objective: "Aprende un bucle simple: repetir un mismo movimiento varias veces.",
    toolbox: ["start", "go", "again2", "again3", "stop"],
    solution: ["start", "again3", "go", "stop"],
    board: {
      cols: 5,
      rows: 5,
      start: { x: 0, y: 2, dir: "E" },
      target: { x: 3, y: 2 },
      collectibles: [{ x: 3, y: 2, label: "tambor" }],
      walls: [{ x: 4, y: 2 }],
    },
  },
  {
    id: "hop-pattern",
    moduleId: "m4-again-loops",
    order: 12,
    title: "Charcos en patron",
    skill: "Bucle con salto",
    character: "hop",
    readingLevel: "Patron de obstaculos",
    source: ["loops"],
    requiresStart: true,
    requiresStop: true,
    story:
      "Hop descubre dos charcos colocados como un patrón: salto, paso, salto, paso. Si el obstáculo se repite, la solución también puede repetirse. En este capítulo Hop y Again hacen equipo por primera vez.",
    dialogue: "¡Boing y paso! ¿Lo repetimos?",
    prompt: "¿Qué pareja de acciones se repite para cruzar?",
    vocabulary: ["obstaculo", "igual", "saltar"],
    objective: "Usa Again para repetir una estrategia contra obstáculos.",
    toolbox: ["start", "hop", "go", "again2", "stop"],
    solution: ["start", "again2", "hop", "go", "stop"],
    board: {
      cols: 6,
      rows: 3,
      start: { x: 0, y: 1, dir: "E" },
      target: { x: 5, y: 1 },
      water: [
        { x: 1, y: 1 },
        { x: 3, y: 1 },
      ],
      collectibles: [{ x: 5, y: 1, label: "gota limpia" }],
    },
  },
  {
    id: "again-stair",
    moduleId: "m4-again-loops",
    order: 13,
    title: "Escalera de eco",
    skill: "Bucle y giro",
    character: "again",
    readingLevel: "Patron con cambio",
    source: ["loops"],
    requiresStart: true,
    requiresStop: true,
    story:
      "La escalera de eco copia todos los movimientos de dos en dos. Primero avanzas con dos pasos iguales; después giras donde manda la pared y repites otros dos. Again ahorra bloques, pero el giro marca el cambio.",
    dialogue: "Repite, gira... ¡y repite otra vez!",
    prompt: "¿Qué debe pasar después de repetir los dos primeros pasos?",
    vocabulary: ["eco", "izquierda", "arriba"],
    objective: "Combina bucle y giro: repetir, cambiar dirección y repetir otra vez.",
    toolbox: ["start", "go", "again2", "left", "right", "stop"],
    solution: ["start", "again2", "go", "left", "again2", "go", "stop"],
    board: {
      cols: 5,
      rows: 5,
      start: { x: 0, y: 3, dir: "E" },
      target: { x: 2, y: 1 },
      collectibles: [{ x: 2, y: 1, label: "eco" }],
      walls: [
        { x: 0, y: 1 },
        { x: 1, y: 1 },
      ],
    },
  },
  {
    id: "finite-infinite",
    moduleId: "m4-again-loops",
    order: 14,
    title: "Codigo largo, no infinito",
    skill: "Control de bucles",
    character: "stop",
    readingLevel: "Advertencia",
    source: ["infinite"],
    requiresStart: true,
    requiresStop: true,
    story:
      "Again está tan contento que repetiría pasos para siempre... ¡y eso sería un código infinito! Stop llega con el freno de mano: repetir está muy bien, pero terminar justo en el sitio correcto está aún mejor.",
    dialogue: "Todo buen código sabe cuándo terminar.",
    prompt: "¿Por qué un programa con repeticiones necesita un final claro?",
    vocabulary: ["largo", "final", "control"],
    objective: "Controla un programa largo: repetir, girar, repetir y cerrar.",
    toolbox: ["start", "go", "again3", "left", "right", "stop"],
    solution: ["start", "again3", "go", "right", "again3", "go", "stop"],
    board: {
      cols: 5,
      rows: 5,
      start: { x: 0, y: 0, dir: "E" },
      target: { x: 3, y: 3 },
      collectibles: [{ x: 3, y: 3, label: "candado" }],
      walls: [{ x: 4, y: 3 }],
    },
  },
  {
    id: "debug-stop",
    moduleId: "m5-code-camp",
    order: 15,
    title: "Depura antes del muro",
    skill: "Depuracion",
    character: "stop",
    readingLevel: "Error controlado",
    source: ["goStop", "instructions"],
    requiresStart: true,
    requiresStop: true,
    story:
      "Byte Brillo ha encontrado un bug: el programa llega hasta la llave... ¡y sigue andando derecho hacia el muro! Depurar es mirar el resultado, descubrir qué paso sobra y cortarlo en el momento exacto.",
    dialogue: "¿Un paso de más? ¡Fuera! Eso es depurar.",
    prompt: "¿Qué bloque corta el programa antes del muro?",
    vocabulary: ["error", "sobrar", "depurar"],
    objective: "Depura una secuencia: llega al premio y detente antes del error.",
    toolbox: ["start", "go", "again2", "stop"],
    solution: ["start", "again2", "go", "stop"],
    board: {
      cols: 5,
      rows: 3,
      start: { x: 0, y: 1, dir: "E" },
      target: { x: 2, y: 1 },
      collectibles: [{ x: 2, y: 1, label: "llave" }],
      walls: [{ x: 3, y: 1 }],
    },
  },
  {
    id: "condition-forest",
    moduleId: "m5-code-camp",
    order: 16,
    title: "Bosque de decisiones",
    skill: "Condiciones",
    character: "nina",
    readingLevel: "Decision",
    source: ["instructions"],
    requiresStart: true,
    requiresStop: true,
    story:
      "En el bosque de las decisiones hay hojas que dicen sí y sombras que dicen no. Nina Nodo nunca adivina: mira la señal de la casilla de delante y solo entonces deja pasar a Go. Así nace una decisión de verdad.",
    dialogue: "Mirar primero, decidir después.",
    prompt: "¿Qué información mira el bloque Si antes de avanzar?",
    vocabulary: ["decision", "informacion", "adivinar"],
    objective: "Usa condiciones para avanzar solo cuando el camino lo permite.",
    toolbox: ["start", "ifSignalGo", "go", "left", "right", "stop"],
    solution: ["start", "ifSignalGo", "go", "left", "ifSignalGo", "stop"],
    board: {
      cols: 5,
      rows: 5,
      start: { x: 0, y: 3, dir: "E" },
      target: { x: 2, y: 2 },
      signals: [
        { x: 1, y: 3 },
        { x: 2, y: 2 },
      ],
      collectibles: [{ x: 2, y: 2, label: "brujula" }],
      walls: [
        { x: 3, y: 3 },
        { x: 1, y: 1 },
      ],
    },
  },
  {
    id: "routine-bridge",
    moduleId: "m5-code-camp",
    order: 17,
    title: "Rutina del puente",
    skill: "Funciones",
    character: "again",
    readingLevel: "Atajo de codigo",
    source: ["loops", "infinite"],
    requiresStart: true,
    requiresStop: true,
    story:
      "El puente de Wonderland tiene un baile secreto: paso, paso y giro a la derecha. La rutina puente guarda ese baile dentro de un solo bloque para usarlo dos veces sin escribir todos los pasos otra vez. ¡Así nacen las funciones!",
    dialogue: "Guarda el baile... ¡y úsalo cuando quieras!",
    prompt: "¿Qué tres pasos contiene la rutina puente?",
    vocabulary: ["rutina", "funcion", "atajo"],
    objective: "Entiende una función: guardar varios pasos y reutilizarlos.",
    toolbox: ["start", "bridge", "go", "stop"],
    solution: ["start", "bridge", "go", "bridge", "go", "stop"],
    board: {
      cols: 5,
      rows: 5,
      start: { x: 0, y: 0, dir: "E" },
      target: { x: 1, y: 3 },
      collectibles: [{ x: 1, y: 3, label: "puente" }],
      walls: [
        { x: 4, y: 0 },
        { x: 4, y: 1 },
        { x: 0, y: 4 },
      ],
    },
  },
  {
    id: "graduation-wondercode",
    moduleId: "m5-code-camp",
    order: 18,
    title: "Gran Wondercode final",
    skill: "Proyecto final",
    character: "byte",
    readingLevel: "Mision completa",
    source: ["rainbow", "animals", "loops", "infinite"],
    requiresStart: true,
    requiresStop: true,
    story:
      "¡Noche de estreno en el teatro Wondercode! Start enciende los focos, Hop cruza el charco del foso, Arty pinta el escenario, Again ahorra pasos, Moo prueba el micrófono y Stop baja el telón. Todo lo que has aprendido, junto en una sola misión.",
    dialogue: "¡Estrellas de código, a escena!",
    prompt: "Ordena la misión: encender, moverse, actuar, repetir y cerrar.",
    vocabulary: ["proyecto", "combinar", "cerrar"],
    objective: "Proyecto final: combinar comandos, acciones, bucles, sonido y cierre.",
    toolbox: ["start", "paint", "go", "hop", "left", "right", "again2", "moo", "stop"],
    solution: ["start", "paint", "go", "hop", "paint", "left", "again2", "go", "right", "go", "moo", "left", "again2", "go", "stop"],
    board: {
      cols: 6,
      rows: 5,
      start: { x: 0, y: 4, dir: "E" },
      target: { x: 4, y: 0 },
      water: [{ x: 2, y: 4 }],
      paintTiles: [
        { x: 0, y: 4 },
        { x: 3, y: 4 },
      ],
      soundGoals: [{ x: 4, y: 2, command: "moo", label: "Moo" }],
      collectibles: [{ x: 4, y: 0, label: "telon" }],
      walls: [
        { x: 5, y: 0 },
        { x: 1, y: 1 },
        { x: 2, y: 1 },
      ],
    },
  },
];
